#Linear regression 

In [ ]:
import pandas as pd

df = pd.read_csv("Advertising.csv", index_col=0)
df

TV  radio  newspaper  sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [ ]:
df.shape # amount of colums and rows

(200, 4)

In [ ]:
x, y = df.drop("sales", axis = 1), df["sales"]
x.head() # all the  features

TV  radio  newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [ ]:
y.head() #labes

1    22.1
2    10.4
3     9.3
4    18.5
5    12.9
Name: sales, dtype: float64

#Test|test split

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

x_train

TV  radio  newspaper
170  284.3   10.6        6.4
98   184.9   21.0       22.0
32   112.9   17.4       38.6
13    23.8   35.1       65.9
36   290.7    4.1        8.5
..     ...    ...        ...
107   25.0   11.0       29.7
15   204.1   32.9       46.0
93   217.7   33.5       59.0
180  165.6   10.0       17.6
103  280.2   10.1       21.4

[140 rows x 3 columns]

In [20]:
x_test
x_test.shape


(60, 3)

In [22]:
y_train.shape, y_test.shape

((140,), (60,))

## Feature scaling

In [34]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(x_train)

scaler

MinMaxScaler()

In [35]:
scaled_x_train = scaler.transform(x_train)
scaled_x_test = scaler.transform(x_test)

scaled_x_train, scaled_x_train.shape 

(array([[0.95908015, 0.21370968, 0.06063618],
        [0.62292864, 0.4233871 , 0.21570577],
        [0.37943862, 0.35080645, 0.38071571],
        [0.07811972, 0.70766129, 0.65208748],
        [0.98072371, 0.08266129, 0.08151093],
        [0.06323977, 0.32258065, 0.21868787],
        [0.99053094, 0.55846774, 0.01491054],
        [0.06087251, 0.24395161, 0.22962227],
        [0.45180927, 0.09879032, 0.08946322],
        [0.08420697, 0.78629032, 0.08946322],
        [0.33716605, 0.19354839, 0.03280318],
        [0.26885357, 0.        , 0.08846918],
        [0.63476496, 0.36491935, 0.25149105],
        [0.59621238, 0.6733871 , 0.38170974],
        [0.42272574, 0.74395161, 0.78429423],
        [0.70645925, 0.41532258, 0.10337972],
        [0.4808928 , 0.59072581, 0.1222664 ],
        [0.62292864, 0.88508065, 0.0139165 ],
        [0.74974636, 0.08669355, 0.49204771],
        [0.81501522, 0.76612903, 0.22763419],
        [0.0557998 , 0.92540323, 0.68588469],
        [0.40514034, 0.57459677, 0

In [36]:
scaled_x_train.min(), scaled_x_train.max()

(np.float64(0.0), np.float64(1.0))

In [37]:
scaled_x_test.min(), scaled_x_test.max()

(np.float64(0.005964214711729622), np.float64(1.1302186878727631))

## Linear regression 

In [38]:
from sklearn.linear_model import LinearRegression 

model = LinearRegression()
model 

LinearRegression()

In [39]:
model.fit(scaled_x_train, y_train)
model.coef_

array([13.02832938,  9.88465985,  0.69237469])

In [40]:
model.intercept_

np.float64(2.7418553248528124)

## Prediction

In [49]:
test_sample_features = scaled_x_test[0].reshape(1,-1)
test_sample_target = y_test.values[0]
test_sample_features, test_sample_target


(array([[0.54988164, 0.63709677, 0.52286282]]), np.float64(16.9))

In [50]:
model.predict(test_sample_features)

array([16.5653963])

In [51]:
test_sample_target

np.float64(16.9)

### prediction on test data

In [52]:
y_pred = model.predict(scaled_x_test)
y_pred.shape

(60,)

In [53]:
y_test.shape

(60,)

In [57]:
y_test[:5].values

array([16.9, 22.4, 21.4,  7.3, 24.7])